# Generated by Django 3.2.23 on 2023-12-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naam_voetballer', models.CharField(max_length=255)),
                ('Actuele_voetbalclub', models.CharField(max_length=255)),
                ('Naam_auteur', models.CharField(max_length=255)),
                ('Datum_invoer', models.DateTimeField(auto_now_add=True)),
                ('Datum_laaste_aanpassing', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
