# Generated by Django 3.2.23 on 2023-12-12 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='Actuele_voetbalclub',
            new_name='actuele_voetbalclub',
        ),
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='Naam_auteur',
            new_name='naam_auteur',
        ),
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='Naam_voetballer',
            new_name='naam_voetballer',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='Datum_invoer',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='Datum_laaste_aanpassing',
        ),
        migrations.AddField(
            model_name='voetbalspelers',
            name='datum_aanpassing',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voetbalspelers',
            name='datum_invoer',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
